version: "3.8"

services:
  reactcrudusers:
    container_name: reactfeusers
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - crudusersnetwork

networks:
  crudusersnetwork:
